# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Data Science - Brian Musisi
email: brianmusisi@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Web Developer - Graphic Artist - User Experience Designer
#baseurl: "/startbootstrap-freelancer-jekyll" # the subpath of your site, e.g. /blog
url: "http://brianmusisi.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: brianmusisi
github_username:  brianmusisi
facebook_username: Brian Musisi
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
address_street: Hannington Rd
address_city: Kampala
address_state: Kampala
address_zip: 256

# Build settings
markdown: kramdown
